### ISSUE TITLE
data crash with poisson loss on Mac M1

### ISSUE THREAD

**Issue by tdhock** [tdhock/binsegRcpp#8]
[82-McGill0058.csv](https://github.com/tdhock/binsegRcpp/files/8391526/82-McGill0058.csv)
unable to reproduce on linux + valgrind. @jkaufy can you provide valgrind output from the computer where you observed the crash? R -d valgrind --vanilla < script_that_crashes.R

**Comment by jkaufy** [comment]
@tdhock 
There is no implementation for valgrind for the Mac M1 yet. I ran the code from the terminal and it seems to be working correctly. The issue must be within RStudio.

**Comment by tdhock** [comment]
weird but great!
