### ISSUE TITLE
Comparison between packages

### ISSUE THREAD

**Issue by Lucas-Prates** [tdhock/binsegRcpp#9]
Hi!

I have implemented the same algorithm in Rcpp for my own package [blockcpd](https://github.com/Lucas-Prates/blockcpd) under the name 'hierseg'.  You said you used std::multiset, while I used std::priority_queue. Albeit it is used for several signals/series, the results should be comparable for the univariated case. 

Software development is a skill I am still developing, so the package structure (and the c++) is a bit crude.

Do you think it would be interesting to compare the performances?

**Comment by tdhock** [comment]
hi @Lucas-Prates priority_queue should in theory have the same asymptotic time complexity as multiset. Yes I think it would be interesting to compare the performances, thanks for the suggestion.

**Comment by tdhock** [comment]
blockcpd timings seem to be asymptotically optimal (same smallest slope on log log plot)
![image](https://user-images.githubusercontent.com/932850/163837500-e616290b-6a39-4774-b06f-99c2246362e5.png)

![image](https://user-images.githubusercontent.com/932850/163837566-0cb640bd-2333-4821-b718-ab74faaf5562.png)

Links to source code used for computing and plotting these timings are here, https://github.com/tdhock/binseg-model-selection#6-apr-2022
